#!/bin/bash
#
# PopSpider BASH CLI script
#
# LICENSE
#
# This source file is subject to the new BSD license that is bundled
# with this package in the file LICENSE.TXT.
# It is also available through the world-wide-web at this URL:
# https://github.com/nicksagona/PopSpider/blob/master/LICENSE.TXT
# If you did not receive a copy of the license and are unable to
# obtain it through the world-wide-web, please send an email
# to info@popphp.org so we can send you a copy immediately.
#
# Possible usage and arguments
#
# ./crawl http://www.domain.com/ -d ./myfolder -o csv -e b,u
#
# -d --dir folder         Set the folder in which to output the file(s) (default: current)
# -o --output html|csv    Set the output to either HTML or CSV (default: HTML)
# -e --elements b,u       Set any additional elements to parse, comma-separated list
# -h --help               Display this help
#

SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
CYG_PATH="$( which cygpath )"

if [ "$CYG_PATH" != "" ]; then
    SCRIPT_PATH="$( cygpath -w $SCRIPT_DIR )\\crawl.php $1 $2 $3 $4 $5 $6 $7"
    SCRIPT_PATH=${SCRIPT_PATH//\\/\/}
else
    SCRIPT_PATH="$SCRIPT_DIR/crawl.php $1 $2 $3 $4 $5 $6 $7"
fi
php $SCRIPT_PATH